version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - goconst
    - misspell
    - unconvert
    - unparam
    - nakedret
    - bodyclose
    - errorlint
    - copyloopvar
    - noctx
    - gosec
    - gocritic

linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: exported
        disabled: true
  gosec:
    excludes:
      - G704
      - G117
      - G101
  gocyclo:
    min-complexity: 15

issues:
  new: false